#!/bin/bash

echo "🔄 Updating Stripe Price IDs in Vercel..."
echo ""

# New Price IDs from your Stripe account
PRICE_LITE="price_1SSnzUHiHOusgnRTr8X3GguO"
PRICE_STANDARD="price_1SSnzVHiHOusgnRTvxdsVzp3"
PRICE_PRO="price_1SSnzVHiHOusgnRTCFkv7RJp"

echo "📝 Instructions to update in Vercel Dashboard:"
echo ""
echo "1. Go to: https://vercel.com/your-team/outboundrevive/settings/environment-variables"
echo "   (or click Settings → Environment Variables in your Vercel project)"
echo ""
echo "2. Find these 3 variables and click 'Edit' on each:"
echo ""
echo "   Variable: STRIPE_PRICE_LITE"
echo "   New Value: ${PRICE_LITE}"
echo ""
echo "   Variable: STRIPE_PRICE_STANDARD"
echo "   New Value: ${PRICE_STANDARD}"
echo ""
echo "   Variable: STRIPE_PRICE_PRO"
echo "   New Value: ${PRICE_PRO}"
echo ""
echo "3. Make sure they're set for: Production, Preview, Development"
echo ""
echo "4. Click 'Save' for each one"
echo ""
echo "5. Redeploy: Go to Deployments → Click '...' → Redeploy"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OR use these Vercel CLI commands (if you have vercel CLI installed):"
echo ""
echo "# Remove old values"
echo "vercel env rm STRIPE_PRICE_LITE production"
echo "vercel env rm STRIPE_PRICE_STANDARD production"
echo "vercel env rm STRIPE_PRICE_PRO production"
echo ""
echo "# Add new values"
echo "echo '${PRICE_LITE}' | vercel env add STRIPE_PRICE_LITE production"
echo "echo '${PRICE_STANDARD}' | vercel env add STRIPE_PRICE_STANDARD production"
echo "echo '${PRICE_PRO}' | vercel env add STRIPE_PRICE_PRO production"
echo ""
echo "# Repeat for preview and development environments"
echo "echo '${PRICE_LITE}' | vercel env add STRIPE_PRICE_LITE preview"
echo "echo '${PRICE_STANDARD}' | vercel env add STRIPE_PRICE_STANDARD preview"
echo "echo '${PRICE_PRO}' | vercel env add STRIPE_PRICE_PRO preview"
echo ""
echo "✅ After updating, wait ~30 seconds for Vercel to redeploy, then test again!"
