import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabaseServer';
import { requireEmailAccount } from '@/lib/email/auth';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * Return suggested DNS records for the domain (SPF, DMARC, optional tracking CNAME).
 * DKIM selector/record would be generated by the sending provider; we return placeholder.
 */
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const auth = await requireEmailAccount(req);
  if (auth instanceof NextResponse) return auth;
  const { accountId } = auth;
  const { id } = await params;

  const { data: row, error } = await supabaseAdmin
    .from('email_domains')
    .select('id, domain')
    .eq('id', id)
    .eq('account_id', accountId)
    .single();

  if (error || !row) return NextResponse.json({ error: 'Domain not found' }, { status: 404 });

  const domain = row.domain as string;
  const records = [
    { type: 'TXT', name: domain, value: `v=spf1 include:_spf.google.com ~all`, purpose: 'SPF (Google); adjust if using other providers' },
    { type: 'TXT', name: `_dmarc.${domain}`, value: 'v=DMARC1; p=none; rua=mailto:dmarc@' + domain, purpose: 'DMARC' },
  ];

  return NextResponse.json({ domain, records });
}
